### ISSUE TITLE
[Feature] Server profiles

### ISSUE THREAD

**Issue by kokbira** [openlierox/openlierox#749]
I suggest to create an way to save configurations of servers hosted "by you", like that:
1. go to netplay
2. select host
3. in that screen, there will be server profiles (e.g. a list of hosts previously created: "My Mortars", "Bottles & Bonuses", "Shock air on library" etc.), instead of current screen that is server settings+player settings
   3.1. server settings+player settings screen would be accessible by a "new" button
   3.2. so, for example, when I select "Bottles & Bonuses", weapons, level, mod and other settings are loaded

Idea posted in LXA forum: http://www.openlierox.net/forum/index.php/topic,13365.0.html

**Comment by albertz** [comment]
This is already possible in 0.59. It is called 'Settings' instead of 'Server profiles'. You can have just any settings there.

That are all the files `*.gamesettings` in the game directory. Just put any further such files there and you will see them in that list.

Via console, I think there is `saveConfig` which can automatically create such a file for you.

**Comment by kokbira** [comment]
I saw that options before. I felt they only adjust some physics settings (and I prefer LX0.56 physics).

But what I say is different. It's about the first screen on Netplay > Host. There would be in that location an option where user can choose one of previous configured servers, including physics. For example, I would like to have that host options for me:
- My classic
- My Mortars 0.56
- My WH40K

All their details must be loaded when I choose one of them. For example (that parameters are not in *.gamesettings files):

My classic
- General server settings
- server name: My classic
- max players: 5
- welcome message: <empty>
- register server: yes
- allow "wants to join" messages: yes
- "wants to join" from banned clients: yes
- allow bots in server: yes
- allow nick changing: yes
- players: kokbira, [cpu] barata 3
- Specific game settings:
- level: run_gump [gus]
- game type: death match
- mod: liero v2.0 [lx]
- settings: lierox 0.56
- autostart: yes
- how many seconds to autostart: 15
- how many players to autostart: 4
- Game settings:
- max kills: 15
- lives: 0 (=infinite)
- loading time: 20
- time limit: 3
- connect during game: yes
- force random weapons: no
- bonuses: yes
- Weapon settings:
- weapon option: retro classic

**Comment by albertz** [comment]
You can do all that via those `*.gamesettings` files. You can just define any available setting in such a file. If you want to use LX 56 physics, just copy the file and extend it by all the other stuff you mentioned.

**Comment by kokbira** [comment]
Interesting. I thought about a GUI solution, but if it is a possible way and it is documented, close that issue.

**Comment by albertz** [comment]
Well, documentation is not really there (except that I wrote about it somewhere at LXA once I think) but it's there and I thought it's more or less obvious how it works when you look at the files. But just from the GUI there is not way to do that.

I'm closing this now but it would be nice if you may extend the documentation (or just the wiki). At some later point we also may add some more options to the GUI to do this but I actually not exactly sure yet how this should look like.
