### ISSUE TITLE
0.59b9: Some hidden settings in a lobby combobox

### ISSUE THREAD

**Issue by kokbira** [openlierox/openlierox#752]
Some details
- OLX Version: 0.59 beta 9
- Type: GUI
- OS: Windows
- I created a lot of *.gamesettings

Procedure:
1. Open OLX and goes to Netplay host lobby screen or Local Play screen
2. Click a combobox called settings (the one that shows Standard, LieroX 0.56, Promode...)

What happens:
- Only some of the existing settings are displayed (alphabetically, the first six)
- Some default settings could be hidden (depends on the created *.gamesettings)
- If you press up/down arrow keys, you can choose hidden settings

Suggested also in http://www.openlierox.net/forum/index.php/topic,13382.msg230006.html#msg230006
Screenshots in my Google Docs: https://docs.google.com/drawings/d/1kEO3fVz0kTW4uuzetg2bBEeJzQIEdgT19I7Tfc0d0BM/edit?hl=pt_BR

---

The dropdown combobox itself has bugs in scrolling when there are too many entries. It doesn't show the current selected one.

**Comment by albertz** [comment]
Can you make some screenshots and post them along with your log file somewhere?

**Comment by kokbira** [comment]
Yes. I'll post in 17 hours, at about GMT 04:00.

I think the problem is that there is no scrollbars designed for this combobox.

**Comment by kokbira** [comment]
that comment and close button :(

**Comment by kokbira** [comment]
Well, I think it would be a easy bug for me.

I downloaded (pull) code with Git, rebased to 0.59 version, but I have some problems now:
- DevCpp project shows a lot of missing files when first opened after rebase
- DevCpp project shows a lot of errors after compile
- I do not know where to start :) (I'm searching for "Settings" text, but it is a much common word... I'm trying some less common text used in other elements in same screen, as "Game type' and "Local play"... I'm reading wiki, but it is much text).

**Comment by albertz** [comment]
Very probably you forgot to install some libraries. There is some documentation (most up-to-date should be the Wiki) about what to install (search for 'Compile'). But this is off-topic for this issue so let's better discuss this elsewhere.

About the code:
The GUI code of the game settings should be in Menu_GameSettings.cpp or sth. like that. Or check Menu_NetHostLobby.cpp (or so).

**Comment by kokbira** [comment]
I edited my first post to include a link to screenshots.

Current status: I have some problems with environment (DevCpp with some files missing on project and DevCpp and VC++ 2010 compile errors with "clean repository")

**Comment by albertz** [comment]
ping? what is/was the state? you had already fixed that?

**Comment by albertz** [comment]
This is probably fixed in cf6a11f.

**Comment by kokbira** [comment]
Sorry, Albert, cause I haven't compiled OLX code successfully yet. I'll try again in the beginning of 2012 and I'll test if it is fixed to transform your "probably" in "sure".
