### ISSUE TITLE
[Feature] Improvements in the race mode

### ISSUE THREAD

**Issue by DaEvil1** [openlierox/openlierox#759]
There should definitely be a countdown at the start of a race. Right now it just starts whenever someone's ready (unless the "wait for all players" is checked.)

It should also be possible to not allow ropehooks to other worms. This could allow for more fair races.

Allow for a custom amount of checkpoints each lap.

Leaderboards that show who is first, to avoid confusion when racing.

Lap, -and racetimes should also be recorded in some way.

**Comment by albertz** [comment]
Can you make separate reports for each request?

**Comment by DaEvil1** [comment]
Done.
