### ISSUE TITLE
Kills and damage are not counted correctly

### ISSUE THREAD

**Issue by karelp** [openlierox/openlierox#768]
In OpenLieroX 0.59 beta 9 servers, the kills and damage are often counted incorrectly. The scoreboard usually reports much lower values than necessary (sometimes even 0/0 at the end of the game). I haven't found a pattern yet but it seems to be connected with the join in game feature as the problem is most apparent on players who join the game in the middle.

**Comment by albertz** [comment]
This is very likely already fixed. (Most of it was rewritten.) Because it is handled all somewhat different now, I'll close this for now. (Btw., isn't this a dup anyway? I think there is a similar report already.)
