### ISSUE TITLE
Spawnpoints are poorly randomized

### ISSUE THREAD

**Issue by karelp** [openlierox/openlierox#769]
The spawn places in OLX 0.58 and 0.59 are somewhat poorly randomized and usually the worms spawn on the same place quite often. It would be nice if the spawning points were less predictable (in deathmatch).

Also, to reduce accidental spawn kills, the spawn point could be chosen in respect to projectile and other player locations.

**Comment by DaEvil1** [comment]
Another thing that could be useful. For 2-3 seconds after spawn, the worm could be immortal and unable to shoot.

**Comment by albertz** [comment]
There is one bug report here and two feature requests. These should be separate issues.

I tried to fix the bug in 0.59 beta10. Not sure though if this was really it. I just changed a float to a double. The code seems correct otherwise.

Reopen if the problem persists.
