### ISSUE TITLE
The GUI is not clickable after switching to Windows and back

### ISSUE THREAD

**Issue by karelp** [openlierox/openlierox#772]
The game GUI stops responding when the user Alt+Tabs out of OLX and then switches back in. This seems to occur only on Windows. The workaround is to right-click in OLX window to regain GUI control.

This seems to be a bug in SDL that should be fixed in the newest version (according to the SDL changelog). It should suffice to update SDL.

**Comment by albertz** [comment]
What newest SDL version? In 0.59 beta10, we use the newest 1.2 SDL version.

**Comment by albertz** [comment]
You mean "Fixed application state handling with ALT-Tab" in SDL 1.2.15? Then it should be fixed already in 0.59 beta10.

**Comment by karelp** [comment]
Yes, that's what I meant.
