### ISSUE TITLE
Linking CXX executable bin/openlierox

### ISSUE THREAD

**Issue by ghost** [openlierox/openlierox#779]
.
.
.
[ 99%] Building C object CMakeFiles/openlierox.dir/libs/lua/ldblib.o
[ 99%] Building C object CMakeFiles/openlierox.dir/libs/lua/ltablib.o
[ 99%] Building C object CMakeFiles/openlierox.dir/libs/lua/lstate.o
[100%] Building C object CMakeFiles/openlierox.dir/libs/lua/lvm.o
Linking CXX executable bin/openlierox
/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/../../../../x86_64-slackware-linux/bin/ld: CMakeFiles/openlierox.dir/src/common/Debug_extended_backtrace.o: undefined reference to symbol 'dladdr@@GLIBC_2.2.5'
/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/../../../../x86_64-slackware-linux/bin/ld: note: 'dladdr@@GLIBC_2.2.5' is defined in DSO /lib64/libdl.so.2 so try adding it to the linker command line
/lib64/libdl.so.2: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
make[2]: **\* [bin/openlierox] Error 1
make[1]: **\* [CMakeFiles/openlierox.dir/all] Error 2
make: **\* [all] Error 2

Any help for this ???

**Comment by pelya** [comment]
You should add -ldl to the linker flags, older versions pf Linux did not
require that lib to be explicitly linked.

**Comment by ghost** [comment]
[ 99%] Building C object CMakeFiles/openlierox.dir/libs/lua/ldblib.o
[ 99%] Building C object CMakeFiles/openlierox.dir/libs/lua/ltablib.o
[ 99%] Building C object CMakeFiles/openlierox.dir/libs/lua/lstate.o
[100%] Building C object CMakeFiles/openlierox.dir/libs/lua/lvm.o
Linking CXX executable bin/openlierox
/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/../../../../x86_64-slackware-linux/bin/ld: cannot find -lboost_signals
collect2: error: ld returned 1 exit status
make[2]: **\* [bin/openlierox] Error 1
make[1]: **\* [CMakeFiles/openlierox.dir/all] Error 2
make: **\* [all] Error 2

**Comment by ghost** [comment]
and this is default boost_signal in  CMakeOlxCommon.cmake

[ 99%] Building C object CMakeFiles/openlierox.dir/libs/lua/ldblib.o
[ 99%] Building C object CMakeFiles/openlierox.dir/libs/lua/ltablib.o
[ 99%] Building C object CMakeFiles/openlierox.dir/libs/lua/lstate.o
[100%] Building C object CMakeFiles/openlierox.dir/libs/lua/lvm.o
Linking CXX executable bin/openlierox
/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/../../../../x86_64-slackware-linux/bin/ld: cannot find -lboost_signals-mt
collect2: error: ld returned 1 exit status
make[2]: **\* [bin/openlierox] Error 1
make[1]: **\* [CMakeFiles/openlierox.dir/all] Error 2
make: **\* [all] Error 2

**Comment by ghost** [comment]
and my cmake configuration : 
DEDICATED_ONLY = OFF
G15 = OFF
X11 = ON
HAWKNL_BUILTIN = ON
LIBZIP_BUILTIN = OFF
LIBLUA_BUILTIN = ON
STLPORT = OFF
GCOREDUMPER = OFF
HASBFD = ON
BREAKPAD = OFF
LINENOISE = ON
CMAKE_C_COMPILER = /usr/bin/cc
CMAKE_C_FLAGS = -O2 -fPIC -ldl
CMAKE_CXX_COMPILER = /usr/bin/c++
CMAKE_CXX_FLAGS = -O2 -fPIC -ldl
MINGW_CROSS_COMPILE = OFF
OLX_VERSION = 0.59_beta10
-- Boost version: 1.54.0
boost-signals not found, trying just boost_signals-mt
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/SBo/openlierox-0.59/build

**Comment by karelp** [comment]
You should install boost libraries on your system, especially the libboost-signals library.

**Comment by ghost** [comment]
in /usr/lib64 , i think it's all there : 
libboost_atomic.so
libboost_atomic.so.1.54.0
libboost_chrono.so
libboost_chrono.so.1.54.0
libboost_context.a
libboost_context.so
libboost_context.so.1.54.0
libboost_coroutine.a
libboost_date_time.so
libboost_date_time.so.1.54.0
libboost_exception.a
libboost_filesystem.so
libboost_filesystem.so.1.54.0
libboost_graph.so
libboost_graph.so.1.54.0
libboost_iostreams.so
libboost_iostreams.so.1.54.0
libboost_locale.so
libboost_locale.so.1.54.0
libboost_log.so
libboost_log.so.1.54.0
libboost_log_setup.so
libboost_log_setup.so.1.54.0
libboost_math_c99.so
libboost_math_c99.so.1.54.0
libboost_prg_exec_monitor.so
libboost_prg_exec_monitor.so.1.54.0
libboost_program_options.so
libboost_program_options.so.1.54.0
libboost_python.so
libboost_python.so.1.54.0
libboost_random.so
libboost_random.so.1.54.0
libboost_regex.so
libboost_regex.so.1.54.0
libboost_serialization.so
libboost_serialization.so.1.54.0
libboost_signals.so
libboost_signals.so.1.54.0
libboost_system.so
libboost_system.so.1.54.0
libboost_test_exec_monitor.a
libboost_thread.so
libboost_thread.so.1.54.0
libboost_timer.so
libboost_timer.so.1.54.0
libboost_unit_test_framework.so
libboost_unit_test_framework.so.1.54.0
libboost_wave.so
libboost_wave.so.1.54.0
libboost_wserialization.so
libboost_wserialization.so.1.54.0

**Comment by pelya** [comment]
But there is no libboost_signals-mt.so, you might need to edit
CMakeLists.txt and remove that -mt suffix.

**Comment by ghost** [comment]
[ 99%] Building C object CMakeFiles/openlierox.dir/libs/lua/ldblib.o
[ 99%] Building C object CMakeFiles/openlierox.dir/libs/lua/ltablib.o
[ 99%] Building C object CMakeFiles/openlierox.dir/libs/lua/lstate.o
[100%] Building C object CMakeFiles/openlierox.dir/libs/lua/lvm.o
Linking CXX executable bin/openlierox
/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/../../../../x86_64-slackware-linux/bin/ld: cannot find -lboost_signals
collect2: error: ld returned 1 exit status
make[2]: **\* [bin/openlierox] Error 1
make[1]: **\* [CMakeFiles/openlierox.dir/all] Error 2
make: **\* [all] Error 2

**Comment by ghost** [comment]
I have tried with different poles ways, including:

SET(LIBS ${LIBS} boost_signals)
SET(LIBS ${LIBS} -lboost_signals)
SET(LIBS ${LIBS} boost_signals-mt)
SET(LIBS ${LIBS} -lboost_signals-mt)
SET(LIBS ${LIBS} "-lboost_signals")
SET(LIBS ${LIBS}/usr/lib64/ boost_signals.so)

but without result ....

**Comment by ghost** [comment]
Ok ... i thing  i did it : 
[ 98%] Building C object CMakeFiles/openlierox.dir/libs/lua/liolib.o
[ 99%] Building C object CMakeFiles/openlierox.dir/libs/lua/ldblib.o
[ 99%] Building C object CMakeFiles/openlierox.dir/libs/lua/ltablib.o
[ 99%] Building C object CMakeFiles/openlierox.dir/libs/lua/lstate.o
[100%] Building C object CMakeFiles/openlierox.dir/libs/lua/lvm.o
Linking CXX executable bin/openlierox
[100%] Built target openlierox

after patch a file CMakeOlxCommon.cmake with this : 

--- openlierox-0.59/CMakeOlxCommon.original.cmake       2014-04-06 13:10:05.423413368 +0300
+++ openlierox-0.59/CMakeOlxCommon.cmake        2014-04-07 00:01:06.134276066 +0300
@@ -320,7 +320,7 @@
                SET(LIBS ${LIBS} ${Boost_signals_LIBRARIES})
        ELSE()
                MESSAGE("boost-signals not found, trying just boost_signals-mt")
-               SET(LIBS ${LIBS} boost_signals-mt)
-               SET(LIBS ${LIBS} "/usr/lib64/libboost_signals.so.1.54.0" "/usr/lib64/libboost_system.so.1.54.0")
      ENDIF()
  ENDIF(BOOST_LINK_STATIC)

but then : 

$ ./start.sh
./start.sh: line 30: ../../bin/openlierox: No such file or directory

or directly from build/bin/openlierox : 

./openlierox
H: SmartPointer collision detector initialized
n: teeStdout: save multithreaded fallback
H: OpenLieroX/0.59_beta10 is starting ...
H: This is a DEBUG build.
n: Free memory: 4723 MB
n: Current time: Mon Apr  7 02:47:06 2014
n: ThreadPool: creating 40 threads ...
n: I have now the following searchpaths (in this order):
n:   /root/.OpenLieroX
n:   .
n:   /usr/share/games/OpenLieroX
n:  And that's all.
n: Reading game options from /root/.OpenLieroX/cfg/options.cfg
n: Will write game options to /root/.OpenLieroX/cfg/options.cfg
n: Default theme is used
n: DONE loading options
n: Installing CrashHandler .. registered simple signal handler
n: Loading network texts... DONE
n: Loading taunts... DONE
E: Error when loading GeoIP database
n: Hello there, I am initializing me now...
n: setting video mode
n: ColorDepth: 32
n: VideoPostProcessor initialisation ... using Dummy video post processor
n: PixelFormat:
n:   BitsPerPixel: 32,  BytesPerPixel: 4
n:   R/G/B/A mask: ff0000/ff00/ff/0
n:   R/G/B/A loss: 0/0/0/8
n:   Colorkey: 0,  Alpha: 255
n: using software surfaces
n: video mode was set successfully
H: OpenAL lib initialized
n: SoundSystem initialised
W: could not load image data/gfx/font.png
E: SystemError: Could not load the fonts
n: Shutting me down...
n: Lua: Registering as non-AUTH
n: Everything was shut down
SmartPointer collision detector de-initialized, everything is freed now

try to run the game but shut down ...

**Comment by ghost** [comment]
Sorry Sorry ..... DONE !!!!

 After copy gamedir /usr/share/games/OpenLieroX !!!!!

**Comment by karelp** [comment]
Glad to hear that you made it work. For OLX to start, it needs to run with working directory that contains all the game data (skins, fonts, levels, etc.), no need to copy it to /usr/share/games.

**Comment by ghost** [comment]
Yes i did it and work very well and it's ready package for Slackware linux to approved 
http://slackbuilds.org/pending/

**Comment by ghost** [comment]
Ok !!! approved and its available from official repo 
http://slackbuilds.org/repository/14.1/games/openlierox/?search=openlierox

**Comment by albertz** [comment]
Very cool, thank you! :)

Btw., that version 0.59 beta10 has known problems with network play. For stable network play, you should submit OLX 0.58.

**Comment by ghost** [comment]
Ooops did not know that ... now I can not downgrade ... will wait for the next version well !!

**Comment by albertz** [comment]
Not sure though when someone of us will have the time to fix those problems in 0.59...

Btw., (I'm not used to Slackware), have you submitted that as version 0.59? That version does not exist (yet). It is just the branch name. Your download link will change whenever someone of us will make a new commit to the 0.59 branch. The current version is 0.59 beta10. Maybe there will follow further betas. And after the betas, there will come 0.59 rc1, and so on. And then, there will be a final 0.59. In the meanwhile, there might come out some 0.60 versions (or maybe we'll make a bigger step and target some 1.0 version or so). This versioning scheme is somewhat similar to the Chrome versioning scheme and their beta and stable release channels.

But as said, you might need to wait a while for any new version.

**Comment by ghost** [comment]
Yes I understand... that every month or so watching all my packages and renewed each time with the new version.

But maybe even fix a package with version 0.58 and if I allow managers of www.slackbuilds.org

**Comment by ghost** [comment]
Done... i downgrade for version 0.58_rc3  : http://slackbuilds.org/cgit/slackbuilds/commit/?id=fe066b173

but i have 0.59_beta10 SlackBuild non official repo for future update : https://github.com/dslackw/SlackBuilds/tree/master/non-SBo/openlierox

Thanks all for support !!!
