### ISSUE TITLE
UDP master server dead?

### ISSUE THREAD

**Issue by lxkurko** [openlierox/openlierox#791]
What is the status of this UDP master server?

`ms.olx.dailyupload.net:23450`

It has been giving these errors for many months:

`n: UDP masterserver failed: cannot resolve domain name ms.olx.dailyupload.net`

Is it dead (domain expired or something) or just "temporarily" down?

**Comment by karelp** [comment]
It is dead AFAIK, you can remove it from your udpmasterservers.txt file.
