### ISSUE TITLE
Taunts and other chat annoyances

### ISSUE THREAD

**Issue by lxkurko** [openlierox/openlierox#814]
Some suggestions related to the in-game chat:

1) Are taunts useful anymore?
Players sometimes press the taunt keys accidentally, resulting in one or more taunt messages. This is especially confusing for new players.
I've never seen anyone using taunts for anything else except spamming the default taunt messages.
Taunts can be sent at a high rate so this can be very annoying.
Android devices have more restricted controls and configuration, so taunts are even less useful on them.

2) Formatting tags that result in a newline, including but not limited to `<br>`, allow annoying impersonation. My suggestion is to disable parsing of these particular tags in the chat box, client-side. These are most likely not needed or useful in the in-game chat.
These tags could be also filtered server-side, but it's complicated. The tags are case-insensitive, and they can contain extra junk inside them, e.g. `<bR asdfghjkl zxcvbnm>`, which makes filtering tricky.

3) To prevent such impersonation without tags, when a long chat message is wrapped into a new line, adding a marker such as * to the beginning of the line would be useful. (URL handling in these situations might become a problem?)

**Comment by pelya** [comment]
Taunts removed in 67ef70d401. br and hr tags are disabled in 3c6b6cdd2.
