### ISSUE TITLE
Package it as a Flatpak and submit it to Athenaeum

### ISSUE THREAD

**Issue by ghost** [openlierox/openlierox#828]
https://github.com/flathub/flathub/wiki/App-Submission

this will also make the game more discoverable to new users

https://gitlab.com/librebob/athenaeum

https://riot.im/app/#/room/#athenaeum:matrix.org

**Comment by albertz** [comment]
Thanks for the suggestion. We might consider it.
Although I'm not quite sure if this is a serious request, or maybe just spam, based on your username ("DontUseGithub").

**Comment by ghost** [comment]
I'm forced to use github because you guys are here, but I'm not happy to use this platform owned by Microsoft, as I don't use any other of their services, such as Windows, Linkedin or any other. No, this is a serious request. Sorry for the confusion.

**Comment by Mailaender** [comment]
See https://github.com/flathub/flathub/pull/3220
